### ISSUE TITLE
Blade files formatting are no more functioning very well after update to v1.20

### ISSUE THREAD

**Issue by adilimudassir** [cjhowe7/laravel-blade-vscode#6] opened 2018-02-25 07:28 UTC
please check this issue

**Comment by cjhowe7** [comment] 2018-10-31 21:22
This extension doesn’t have any support for formatting Blade templates, but I can look into adding this.

**Comment by cjhowe7** [comment] 2018-10-31 21:22
This seems to be a duplicate of #1. I can reppen this if that’s not true.

**Closed by cjhowe7** 2018-10-31 21:22 UTC
